In [10]:
import tensorflow as tf
import numpy as np

In [11]:
xy = np.loadtxt('multi-variable linear regression example.csv',
                delimiter = ',', dtype = np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [12]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [13]:
x = tf.placeholder(tf.float32, shape = [None, 3])
y = tf.placeholder(tf.float32, shape = [None, 1])

w = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [14]:
hypothesis = tf.matmul(x, w) + b

In [15]:
cost = tf.reduce_mean(tf.square(hypothesis - y))

In [16]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.00001)
train = optimizer.minimize(cost)

In [17]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [19]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train],
    feed_dict = {x: x_data, y: y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  3.7550666 
Prediction:
 [[152.9296 ]
 [183.11702]
 [180.81606]
 [197.66452]
 [138.6665 ]
 [102.88994]]
10 Cost:  3.7493083 
Prediction:
 [[152.92607]
 [183.11899]
 [180.81485]
 [197.66278]
 [138.66989]
 [102.89251]]
20 Cost:  3.743599 
Prediction:
 [[152.92256]
 [183.12093]
 [180.81361]
 [197.66103]
 [138.67325]
 [102.89507]]
30 Cost:  3.737882 
Prediction:
 [[152.91908]
 [183.12291]
 [180.81242]
 [197.65929]
 [138.67662]
 [102.89763]]
40 Cost:  3.7322311 
Prediction:
 [[152.9156 ]
 [183.12483]
 [180.81122]
 [197.65758]
 [138.67998]
 [102.90016]]
50 Cost:  3.726539 
Prediction:
 [[152.91212]
 [183.12679]
 [180.81001]
 [197.65582]
 [138.68333]
 [102.90268]]
60 Cost:  3.720933 
Prediction:
 [[152.90868]
 [183.12872]
 [180.80882]
 [197.6541 ]
 [138.68666]
 [102.9052 ]]
70 Cost:  3.715328 
Prediction:
 [[152.90524]
 [183.13065]
 [180.80762]
 [197.65237]
 [138.69   ]
 [102.90771]]
80 Cost:  3.709758 
Prediction:
 [[152.90181]
 [183.13258]
 [180.80646]
 [197.65067]
 [138.69333]
 [10

900 Cost:  3.324032 
Prediction:
 [[152.6568 ]
 [183.27237]
 [180.72371]
 [197.52068]
 [138.94072]
 [103.08151]]
910 Cost:  3.3200607 
Prediction:
 [[152.65419]
 [183.27386]
 [180.72285]
 [197.51918]
 [138.94344]
 [103.08323]]
920 Cost:  3.3161013 
Prediction:
 [[152.65163 ]
 [183.27538 ]
 [180.72202 ]
 [197.51775 ]
 [138.94618 ]
 [103.084946]]
930 Cost:  3.3121526 
Prediction:
 [[152.64906]
 [183.27687]
 [180.72118]
 [197.51628]
 [138.9489 ]
 [103.08663]]
940 Cost:  3.308252 
Prediction:
 [[152.64651]
 [183.27835]
 [180.72034]
 [197.51483]
 [138.95161]
 [103.08835]]
950 Cost:  3.3043156 
Prediction:
 [[152.64395]
 [183.27983]
 [180.7195 ]
 [197.51337]
 [138.95433]
 [103.09002]]
960 Cost:  3.300415 
Prediction:
 [[152.6414  ]
 [183.28133 ]
 [180.71866 ]
 [197.51192 ]
 [138.95703 ]
 [103.091705]]
970 Cost:  3.2965488 
Prediction:
 [[152.63887]
 [183.28279]
 [180.71783]
 [197.51045]
 [138.95972]
 [103.09338]]
980 Cost:  3.292673 
Prediction:
 [[152.63635]
 [183.28427]
 [180.71701]
 [197.

1720 Cost:  3.0405617 
Prediction:
 [[152.47177]
 [183.38214]
 [180.66467]
 [197.40889]
 [139.14604]
 [103.19807]]
1730 Cost:  3.0375423 
Prediction:
 [[152.46982]
 [183.38333]
 [180.66408]
 [197.40761]
 [139.14833]
 [103.19921]]
1740 Cost:  3.0345688 
Prediction:
 [[152.46786 ]
 [183.3845  ]
 [180.66347 ]
 [197.40634 ]
 [139.15059 ]
 [103.200356]]
1750 Cost:  3.0315526 
Prediction:
 [[152.46594]
 [183.38571]
 [180.66289]
 [197.40509]
 [139.1529 ]
 [103.20149]]
1760 Cost:  3.0285952 
Prediction:
 [[152.46402 ]
 [183.38686 ]
 [180.6623  ]
 [197.40382 ]
 [139.15515 ]
 [103.202614]]
1770 Cost:  3.0256073 
Prediction:
 [[152.46211]
 [183.38805]
 [180.6617 ]
 [197.40257]
 [139.15742]
 [103.20373]]
1780 Cost:  3.0226498 
Prediction:
 [[152.46017]
 [183.3892 ]
 [180.66113]
 [197.4013 ]
 [139.15968]
 [103.20484]]
1790 Cost:  3.0196705 
Prediction:
 [[152.45828]
 [183.39038]
 [180.66054]
 [197.40005]
 [139.16196]
 [103.20594]]
1800 Cost:  3.0167515 
Prediction:
 [[152.45638 ]
 [183.39154 ]
 [18

In [20]:
print("Your score will be ", sess.run(hypothesis,
                                     feed_dict = {x: [[100, 70, 101]]}))
print("Your score will be ", sess.run(hypothesis,
                                     feed_dict = {x: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[182.5755]]
Your score will be  [[169.85902]
 [178.16014]]
