In [3]:
import tensorflow as tf

In [4]:
x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5],
          [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0],
          [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

In [5]:
x = tf.placeholder(tf.float32, [None, 4])
y = tf.placeholder(tf.float32, [None, 3])
nb_classes = 3

w = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [8]:
hypothesis = tf.nn.softmax(tf.matmul(x, w) + b)

In [17]:
cost = tf.reduce_mean(-tf.reduce_sum(y * tf.log(hypothesis), axis = 1))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.5).minimize(cost)

In [21]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(train, feed_dict = {x: x_data, y: y_data})
        if step % 20 == 0:
            print(step, sess.run(cost, feed_dict = {x: x_data, y: y_data}))

0 6.026829
20 5.6921716
40 4.2095747
60 3.851689
80 2.8433537
100 2.262959
120 1.5461278
140 1.6926833
160 4.3975677
180 2.4559455
200 0.90620846
220 5.007102
240 4.995214
260 4.3657374
280 5.4225416
300 5.2909036
320 5.594092
340 1.6712475
360 0.5763125
380 1.2595942
400 1.5392123
420 0.5586282
440 2.928147
460 2.1680157
480 2.5076985
500 0.7585139
520 0.32154074
540 1.7468293
560 0.24600837
580 0.76357543
600 1.1154565
620 0.23957725
640 1.988886
660 0.679237
680 3.5523498
700 0.38359365
720 2.4379487
740 1.9591755
760 3.3173227
780 1.2512951
800 2.1094394
820 1.4867613
840 2.187496
860 0.72716576
880 0.76150495
900 1.224191
920 2.5997245
940 0.04007563
960 0.019617032
980 0.015715584
1000 0.013844102
1020 0.012652669
1040 0.011794093
1060 0.011138675
1080 0.010623403
1100 0.01021213
1120 0.009881651
1140 0.009615758
1160 0.00940219
1180 0.009231199
1200 0.009094564
1220 0.008985354
1240 0.008897649
1260 0.008826617
1280 0.00876811
1300 0.008719022
1320 0.008676883
1340 0.008639744
1

In [25]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    result = sess.run(hypothesis, feed_dict={
                      x: [[2, 4, 7, 6], [1, 2, 1, 2], [3, 1, 1, 1]]})
    print(result, sess.run(tf.arg_max(result, 1)))

[[1.6013142e-03 2.8427664e-04 9.9811447e-01]
 [1.1594060e-01 1.5861852e-01 7.2544086e-01]
 [3.1340595e-02 9.0051842e-01 6.8141088e-02]] [2 2 1]
