In [1]:
import tensorflow as tf

In [2]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

In [3]:
x = tf.placeholder(tf.float32, shape = [None, 3])
y = tf.placeholder(tf.float32, shape= [None, 1])

In [4]:
w = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')
hypothesis = tf.matmul(x, w) + b

In [5]:
cost = tf.reduce_mean(tf.square(hypothesis - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.0000007)
train = optimizer.minimize(cost)

In [6]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [7]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {x: x_data, y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)

0 Cost:  131444.58 
Prediction: 
 [[-169.54897]
 [-202.4175 ]
 [-200.08644]
 [-218.89848]
 [-153.17853]]
10 Cost:  70295.23 
Prediction: 
 [[ -83.10772]
 [ -98.52137]
 [ -97.71592]
 [-107.41953]
 [ -73.93193]]
20 Cost:  37593.242 
Prediction: 
 [[-19.8939  ]
 [-22.542898]
 [-22.853117]
 [-25.895807]
 [-15.979457]]
30 Cost:  20104.586 
Prediction: 
 [[26.333878]
 [33.019608]
 [31.89348 ]
 [33.721878]
 [26.400782]]
40 Cost:  10751.843 
Prediction: 
 [[60.139885]
 [73.652084]
 [71.92926 ]
 [77.319855]
 [57.393154]]
50 Cost:  5750.1025 
Prediction: 
 [[ 84.86194 ]
 [103.366325]
 [101.207115]
 [109.20273 ]
 [ 80.05767 ]]
60 Cost:  3075.225 
Prediction: 
 [[102.94099 ]
 [125.09617 ]
 [122.61781 ]
 [132.51845 ]
 [ 96.632095]]
70 Cost:  1644.7328 
Prediction: 
 [[116.16202]
 [140.98703]
 [138.27525]
 [149.56903]
 [108.75286]]
80 Cost:  879.7201 
Prediction: 
 [[125.830444]
 [152.60794 ]
 [149.72545 ]
 [162.03802 ]
 [117.61671 ]]
90 Cost:  470.60138 
Prediction: 
 [[132.90085]
 [161.10622]
 [15

900 Cost:  0.2890997 
Prediction: 
 [[152.13606]
 [184.23964]
 [180.88524]
 [195.97147]
 [141.74628]]
910 Cost:  0.28905085 
Prediction: 
 [[152.13597]
 [184.2397 ]
 [180.8852 ]
 [195.97145]
 [141.74637]]
920 Cost:  0.28900504 
Prediction: 
 [[152.13588]
 [184.23979]
 [180.88518]
 [195.97144]
 [141.74644]]
930 Cost:  0.28896683 
Prediction: 
 [[152.13579]
 [184.23985]
 [180.88516]
 [195.97144]
 [141.74654]]
940 Cost:  0.28892577 
Prediction: 
 [[152.13571]
 [184.23991]
 [180.88513]
 [195.97142]
 [141.74661]]
950 Cost:  0.2888831 
Prediction: 
 [[152.13562]
 [184.23999]
 [180.88512]
 [195.9714 ]
 [141.7467 ]]
960 Cost:  0.28883564 
Prediction: 
 [[152.13553]
 [184.24005]
 [180.88507]
 [195.9714 ]
 [141.74678]]
970 Cost:  0.28879935 
Prediction: 
 [[152.13544]
 [184.24011]
 [180.88506]
 [195.97137]
 [141.74686]]
980 Cost:  0.28875577 
Prediction: 
 [[152.13535]
 [184.24017]
 [180.88503]
 [195.97137]
 [141.74695]]
990 Cost:  0.28870946 
Prediction: 
 [[152.13525]
 [184.24025]
 [180.885  ]

 [141.75317]]
1780 Cost:  0.2854111 
Prediction: 
 [[152.12794]
 [184.24518]
 [180.88269]
 [195.96997]
 [141.75325]]
1790 Cost:  0.28537405 
Prediction: 
 [[152.12784]
 [184.24522]
 [180.88266]
 [195.96992]
 [141.75333]]
1800 Cost:  0.28533286 
Prediction: 
 [[152.12775]
 [184.24529]
 [180.88263]
 [195.96991]
 [141.7534 ]]
1810 Cost:  0.28528684 
Prediction: 
 [[152.12766]
 [184.24536]
 [180.8826 ]
 [195.96991]
 [141.75348]]
1820 Cost:  0.2852548 
Prediction: 
 [[152.12756]
 [184.24539]
 [180.88257]
 [195.9699 ]
 [141.75356]]
1830 Cost:  0.2852098 
Prediction: 
 [[152.12747]
 [184.24548]
 [180.88255]
 [195.96988]
 [141.75363]]
1840 Cost:  0.28516725 
Prediction: 
 [[152.12737]
 [184.24553]
 [180.8825 ]
 [195.96985]
 [141.75371]]
1850 Cost:  0.28512126 
Prediction: 
 [[152.12727]
 [184.2456 ]
 [180.88248]
 [195.96985]
 [141.75378]]
1860 Cost:  0.28508487 
Prediction: 
 [[152.12718]
 [184.24565]
 [180.88245]
 [195.96982]
 [141.75386]]
1870 Cost:  0.2850439 
Prediction: 
 [[152.12709]
 [1